#ifndef FLOW_HPP
    #define FLOW_HPP
    
    #include <iostream>
    #include <string>
    
    #include "System.hpp"

    /// @brief A Flow changes systems energy.
    class Flow
    {
        public:
            virtual ~Flow() {}
            
            virtual Flow &operator=(const Flow &obj) = 0;
            /// @brief getter of the name
            virtual string getName() const = 0;
            /// @brief setter of the name
            virtual void setName(const string name) = 0;
            /// @brief getter of the origin system
            virtual System *getOrigin() const = 0;
            /// @brief setter of the origin system
            virtual void setOrigin(System *origin) = 0;
            /// @brief getter of the target system
            virtual System *getTarget() const = 0;
            /// @brief setter of the target system
            virtual void setTarget(System *target) = 0;

            /// @brief Execute an equation.
            ///
            /// To set an equation, create a subclass and implement this method.
            /// @return Value generated by the equation.
            virtual double execute() = 0;
    };
#endif