#ifndef FLOW_IMPL_HPP
    #define FLOW_IMPL_HPP
    
    #include <iostream>
    #include <string>
    
    #include "Flow.hpp"

    /// @brief Implementation of Flow's methods
    class Flow_Impl : public Flow
    {
        public:
            Flow_Impl();
            virtual ~Flow_Impl();

        protected:
            string name;
            System *origin;
            System *target;

        public:
            Flow_Impl(const string name, System *origin, System *target);

            Flow_Impl(Flow &obj);
            Flow &operator=(const Flow &obj);

            string getName() const;
            void setName(const string name);
            System *getOrigin() const;
            void setOrigin(System *origin);
            System *getTarget() const;
            void setTarget(System *target);

            /// @brief Execute an equation.
            ///
            /// To set an equation, create a subclass and implement this method.
            /// @return Value generated by the equation.
            virtual double execute() = 0;
    };
#endif